# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scene Connector
name : "SoftLeitner"
email: softleitner@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  scene connector unity asset
minimal_mistakes_skin: neon
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "SoftLeitner"
      icon: "fas fa-home"
      url: "https://softleitner.com/"
    - label: "Store"
      icon: "fab fa-fw fa-unity"
      url: "https://assetstore.unity.com/packages/slug/191644"
    - label: "Forum"
      icon: "fas fa-comments"
      url: "https://forum.unity.com/threads/released-scene-connector.1082615/"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/8dkbGFsbDY"
    - label: "Support"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:softleitner@gmail.com"
    - label: "Coffee"
      icon: "fas fa-coffee"
      url: "https://www.buymeacoffee.com/softleitner"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
